# Generated by Codex on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_upgrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="artisanprofile",
            name="account_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="artisanprofile",
            name="bank_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="artisanprofile",
            name="iban",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="artisanprofile",
            name="payout_full_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
