# Generated by Django 6.0.6 on 2026-06-19 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_artisan_payout_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisanprofile',
            name='profession',
        ),
    ]
